# Generated by Django 4.2.1 on 2023-08-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_mail_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
