# Generated by Django 4.2.1 on 2023-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.IntegerField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
