# Generated by Django 4.2.1 on 2023-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_basket_options_alter_carditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=2, verbose_name='Наименование'),
        ),
    ]
