# Generated by Django 4.2.1 on 2023-08-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=2, verbose_name='Размер'),
        ),
    ]
