# Generated by Django 4.2.1 on 2023-08-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.ManyToManyField(to='main.size'),
        ),
    ]
