# Generated by Django 4.2.1 on 2023-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='human',
            field=models.CharField(choices=[(0, 'Для мужчин'), (1, 'Для женщин'), (2, 'Унисекс')], default=0, max_length=15, verbose_name='Для кого ?'),
        ),
    ]
