# Generated by Django 4.2.1 on 2023-08-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='human',
            field=models.CharField(choices=[('Для мужчин', 'Для мужчин'), ('Для женщин', 'Для женщин'), ('Унисекс', 'Унисекс')], default='Для мужчин', max_length=15, verbose_name='Для кого ?'),
        ),
    ]
